export const getGqlResource = (resource: string) => {
  switch (resource) {
    case "admin_users":
      return "AdminUser";
    case "datacenters":
      return "Datacenter";
    case "streams":
      return "Stream";
    case "region":
      return "Region";
    case "images":
      return "Image";
    case "pages_and_attributes/questions":
      return "Question";
    case "media_content/tv/channels/channels/:channelId/channel_versions":
      return "ChannelVersion";
    case "media_content/tv/channels/channel_versions/:channelVersionId/:epgSourceId/:startAt/program_events":
      return "ProgramEvent";
    case "media_content/tv/channels/channels":
      return "Channel";
    case "media_content/tv/channels/live_streams":
      return "LiveStream";
    case "media_content/tv/channels/channel_positions_overrides":
      return "ChannelPositionOverride";
    case "media_content/tv/channels/blackouts":
      return "Blackout";
    case "media_content/tv/tv_shows/epg_sources":
      return "EpgSource";
    case "media_content/tv/tv_shows/tv_programs":
      return "Epg";
    case "media_content/tv/tv_shows/epg_local_events":
      return "EpgLocalEvent";
    case "media_content/video/video_files":
      return "VideoFile";
    case "media_content/video/movies":
      return "Movie";
    case "media_content/attributes/providers/studios":
      return "Studio";
    case "media_content/attributes/languages":
      return "Language";
    case "media_content/attributes/providers/content_providers":
      return "ExternalCatalog";
    case "media_content/attributes/providers/right_holders":
      return "RightHolder";
    case "media_content/attributes/genres":
      return "Genre";
    case "media_content/attributes/people":
      return "Person";
    case "media_content/attributes/programs_types":
      return "ProgramType";
    case "media_content/attributes/labels":
      return "Label";
    case "media_content/radio/radio_stations":
      return "RadioStation";
    case "media_content/radio/radio_live_streams":
      return "RadioLiveStream";
    case "media_content/video/seasons/:seasonId/episodes":
      return "Episode";
    case "media_content/video/series/:seriesId/seasons":
      return "Season";
    case "media_content/video/series":
      return "Series";
    case "media_content/audio/audio_shows/:audioShowId/parts":
      return "Part";
    case "media_content/audio/audio_shows":
      return "AudioShow";
    case "episodes":
      return "Episode";
    case "api_clients":
      return "ApiClient";
    case "media_content/news":
      return "News";
    case "castMembers":
      return "CastMember";
    case "countries":
      return "Country";
    case "production_countries":
      return "ProductionCountry";
    default:
      throw new Error(`Unknown resource ${resource}`);
  }
};
